### ISSUE TITLE
Port number specifier syntax

### ISSUE THREAD

**Issue by shun159** [trema/phut#14]
@yasuhito 
表題のとおりですが、
仮想NW環境で、デバイスへの接続にポート指定が必要な場合も
あるかと存じます。

ぜひとも、TODOに加えて頂ければ幸いです。

**Comment by yasuhito** [comment]
ポート番号の指定ですが、設定ファイルで `link name1, name2` が登場した順にスイッチポートの 1, 2, ... に挿さるようにしました。

どのように動くか詳しくは、↓の最後のシナリオに書いてあります。
https://github.com/trema/phut/blob/develop/features/dsl_link.feature

最初、なにか特別な文法を導入しようかと思っていましたが、指定したリンクと指定していないものが混ざると非常に分かりにくいので、このように暗黙的に決めることにしました。

**Comment by shun159** [comment]
ありがとうございます！
試してみます。
